
depth_par:
    key: 'pres'
    title: 'Tryck [dbar]'
    data_par: 'PRES_CTD [dbar]'
    qf_par: 'Q_PRES_CTD'

pars:
  -
    key: 'temp1'
    title: 'Temperatur [°C (ITS-90)]'
    data_par: 'TEMP_CTD [°C (ITS-90)]'
    qf_par: 'Q_TEMP_CTD'
    color: 'blue'
    xmin: 0
    xmax: 20

  -
    key: 'salt1'
    title: 'Salinitet [psu]'
    data_par: 'SALT_CTD [psu]'
    qf_par: 'Q_SALT_CTD'
    color: 'red'
    xmin: 0
    xmax: 20
  
  -
    key: 'doxy1'
    title: 'Syre [ml/l]'
    data_par: 'DOXY_CTD [ml/l]'
    qf_par: 'Q_DOXY_CTD'
    color: 'grey'
    xmin: 0
    xmax: 10
    
  -
    key: 'flour'
    title: 'Fluoroscence [mg/m3]'
    data_par: 'CHLFLUO_CTD [mg/m3]'
    qf_par: 'Q_CHLFLUO_CTD'
    color: 'green'
    xmin: 0
    xmax: 10
