
depth_par:
    key: 'pres'
    title: 'Tryck [dbar]'
    data_par: 'PRES_CTD [dbar]'
    qf_par: 'Q_PRES_CTD'

pars:
  -
    key: 'temp1'
    title: 'Temperatur [°C (ITS-90)]'
    data_par: 'TEMP_CTD [°C (ITS-90)]'
    qf_par: 'Q_TEMP_CTD'
    color: 'blue'
    xmin: 0
    xmax: 20

  -
    key: 'salt1'
    title: 'Salinitet [psu]'
    data_par: 'SALT_CTD [psu]'
    qf_par: 'Q_SALT_CTD'
    color: 'red'
    xmin: 0
    xmax: 40

  -
    key: 'temp_diff'
    title: 'Temperatur diff, 2-1 [°C (ITS-90)]'
    data_par: 'TEMP2_CTD [°C (ITS-90)]--TEMP_CTD [°C (ITS-90)]'
    qf_par: 'Q_TEMP2_CTD--Q_TEMP_CTD'
    color: 'green'
    xmin: -0.2
    xmax: 0.2
    
  -
    key: 'salt_diff'
    title: 'Salinitet diff, 2-1 [psu]'
    data_par: 'SALT2_CTD [psu]--SALT_CTD [psu]'
    qf_par: 'Q_SALT2_CTD--Q_SALT_CTD'
    color: 'brown'
    xmin: -0.2
    xmax: 0.2
