@startuml

title Class diagram: seabird

class __init__._get_paths_in_directory_tree #EB9A32 {
	
==
	
}

class __init__.copy_file_object #EB9A32 {
	
==
	
}

class __init__.copy_package #EB9A32 {
	
==
	
}

class __init__.get_file_names_in_directory #EB9A32 {
	
==
	
}

class __init__.get_file_object_for_path #EB9A32 {
	
==
	
}

class __init__.get_package_collection_for_directory #EB9A32 {
	
==
	
}

class __init__.get_package_for_file #EB9A32 {
	
==
	
}

class __init__.get_packages_from_file_list #EB9A32 {
	
==
	
}

class __init__.get_packages_in_directory #EB9A32 {
	
==
	
}

class __init__.modify_cnv_down_file #EB9A32 {
	
==
	
}

class __init__.rename_file_object #EB9A32 {
	
==
	
}

class __init__.rename_package #EB9A32 {
	
==
	
}

class __init__.update_package_with_files_in_directory #EB9A32 {
	
==
	
}

class bl_file.BlFile #C8C6B1 {
	+suffix, @ca
	-_number_of_bottles
	-_number_of_bottles, @ca
	number_of_bottles, @p
==
	-_save_attributes()
	-_save_info_from_file()
}

class btl_file.BtlFile #5C9F84 {
	+suffix, @ca
==
	-_save_info_from_file()
}

class cnv_file.CnvFile #F84644 {
	+col_dens
	+col_dens2
	+col_depth
	+col_pres
	+col_sv
	+header
	+header, @ca
	+header_date_format, @ca
	+suffix, @ca
	-_header_cruise_info
	-_header_cruise_info, @ca
	-_header_datetime
	-_header_datetime, @ca
	-_header_form
	-_header_form, @ca
	-_header_lat
	-_header_lat, @ca
	-_header_lon
	-_header_lon, @ca
	-_header_names
	-_header_names, @ca
	-_header_station
	-_header_station, @ca
	-_nr_data_lines
	-_parameters
	-_parameters, @ca
	-_sensor_info
	-_sensor_info, @ca
	-_xml_tree
	-_xml_tree, @ca
	data_lines, @p
	density_data, @p
	depth_data, @p
	header_lines, @p
	parameters, @p
	pressure_data, @p
	sound_velocity_data, @p
==
	+get_save_name()
	+string_match_header_form()
	-_get_datetime()
	-_save_attributes()
	-_save_columns()
	-_save_info_from_file()
}

class cnv_file.Header #F84644 {
	+linebreak
	-_lines
	lines, @p
==
	+add_line()
}

class cnv_file.HeaderName #F84644 {
	-_code
	-_code, @ca
	-_index
	-_index, @ca
	-_parameter
	-_parameter, @ca
	-_string
	-_string, @ca
	code, @p
	index, @p
	parameter, @p
==
	-__repr__()
	-__str__()
	-_save_info()
}

class cnv_file.Parameter #F84644 {
	+active
	+cnv_info_object
	+info
	+sample_value
	+use_cnv_info_format
	-_data
	-_nr_decimals
	-_tot_value_length
	-_value_format
	data, @p
==
	+add_data()
	+change_name()
	+get_format()
	+get_value_as_string_for_index()
	+set_active()
	+set_value_length()
	-__getattr__()
	-__getitem__()
	-__repr__()
	-_set_nr_decimals()
}

class file.SeabirdFile #E23D5C {
	+name_match
	+path
	+path, @ca
	+suffix, @ca
	-_attributes
	-_attributes, @ca
	-_key
	-_lines
	-_lines, @ca
	-_path_info
	-_path_info, @ca
	attributes, @p
	datetime, @p
	key, @p
	lines, @p
	md5, @p
	name, @p
	pattern, @p
	stem, @p
==
	+get_proper_name()
	+get_proper_path()
	+get_save_name()
	+get_save_path()
	+save_file()
	-__call__()
	-__eq__()
	-__repr__()
	-__str__()
	-_fixup()
	-_get_datetime()
	-_get_datetime_from_path()
	-_load_file()
	-_save_attributes()
	-_save_info_from_file()
}

class file.UnrecognizedFile #E23D5C {
	
==
	
}

class hdr_file.HdrFile #1289C6 {
	+date_format, @ca
	+suffix, @ca
	-_cruise_info
	-_cruise_info, @ca
	-_datetime
	-_datetime, @ca
	-_header_form
	-_header_form, @ca
	-_lat
	-_lon
	-_station
	-_station, @ca
==
	-_get_datetime()
	-_save_attributes()
	-_save_info_from_file()
}

class hex_file.HexFile #2BF053 {
	+suffix, @ca
==
	-_save_attributes()
	-_save_info_from_file()
}

class jpg_file.JpgFile #6BAAD4 {
	+suffix, @ca
==
	
}

class mapping.get_instrument_mapping #0D154B {
	
==
	
}

class mapping.get_ship_mapping #0D154B {
	
==
	
}

class mapping.get_year_mapping #0D154B {
	
==
	
}

class modify.InvalidFileToModify #25EF63 {
	
==
	
}

class modify.Modify #25EF63 {
	-_file
==
	+modify()
	-_modify()
	-_validate()
}

class modify_cnv.Header #50A7CD {
	
==
	+append_to_row(), @sm
	+get_row_index_for_matching_string(), @sm
	+insert_row_after(), @sm
	+old_insert_row_after(), @sm
	+replace_row(), @sm
	+replace_string_at_index(), @sm
}

class modify_cnv.ModifyCnv #50A7CD {
	+g, @ca
	+missing_value, @ca
	+missing_value_str, @ca
	-_header_lines
==
	-_change_parameter_name()
	-_get_calculated_true_depth()
	-_get_mean_sound_velocity()
	-_get_parameter_name_matching_string()
	-_modify()
	-_modify_depth()
	-_modify_fluorescence()
	-_modify_header_information()
	-_modify_irradiance()
	-_set_lines()
	-_validate()
}

class mvp_files.RawFile #13C0F1 {
	+suffix, @ca
==
	-_save_attributes()
	-_save_info_from_file()
}

class package.Operations #533170 {
	
==
	-__call__()
	-__eq__()
	-__ge__()
	-__gt__()
	-__le__()
	-__lt__()
}

class package.Package #533170 {
	+RAW_FILES_EXTENSIONS, @ca
	-_config_file_suffix
	-_files
	attributes, @p
	file_names, @p
	files, @p
	key, @p
	key_info, @p
	pattern, @p
==
	+add_file()
	+get_file()
	+get_file_path()
	+get_files()
	+get_plot_files()
	+get_raw_files()
	+path()
	+set_key()
	+validate()
	-__call__()
	-__getitem__()
	-__str__()
	-_set_config_suffix()
}

class package_collection.PackageCollection #CAE812 {
	-_packages
	keys, @p
	nr_files, @p
	packages, @p
==
	+add_package()
	+add_packages()
	+missing()
	-__call__()
	-__getitem__()
}

class patterns.get_cruise_match #4FAC81 {
	
==
	
}

class patterns.get_cruise_match_dict #4FAC81 {
	
==
	
}

class patterns.get_file_stem_match #4FAC81 {
	
==
	
}

class ros_file.RosFile #A204D8 {
	+suffix, @ca
==
	-_save_info_from_file()
}

class xmlcon_file.XmlconFile #30DD49 {
	+suffix, @ca
	-_sensor_info
	-_sensor_info, @ca
	-_tree
	-_tree, @ca
	instrument, @p
	instrument_number, @p
==
	-_save_attributes()
	-_save_info_from_file()
}

class xmlcon_parser.get_instrument #73E145 {
	
==
	
}

class xmlcon_parser.get_instrument_number #73E145 {
	
==
	
}

class xmlcon_parser.get_parser_from_file #73E145 {
	
==
	
}

class xmlcon_parser.get_parser_from_string #73E145 {
	
==
	
}

class xmlcon_parser.get_sensor_info #73E145 {
	
==
	
}


bl_file.BlFile <|-- file.SeabirdFile

btl_file.BtlFile <|-- file.SeabirdFile

cnv_file.CnvFile <|-- file.SeabirdFile

file.SeabirdFile <|-- ABC

file.UnrecognizedFile <|-- Exception

hdr_file.HdrFile <|-- file.SeabirdFile

hex_file.HexFile <|-- file.SeabirdFile

jpg_file.JpgFile <|-- file.SeabirdFile

modify.InvalidFileToModify <|-- Exception

modify.Modify <|-- ABC

modify_cnv.ModifyCnv <|-- modify.Modify

mvp_files.RawFile <|-- file.SeabirdFile

package.Package <|-- package.Operations

ros_file.RosFile <|-- file.SeabirdFile

xmlcon_file.XmlconFile <|-- file.SeabirdFile

cnv_file.CnvFile o-- cnv_file.Header
cnv_file.CnvFile o-- cnv_file.HeaderName
cnv_file.CnvFile o-- cnv_file.Parameter
cnv_file.CnvFile o-- cnv_file.Parameter
cnv_file.CnvFile o-- modify_cnv.Header
cnv_file.CnvFile o-- patterns.get_cruise_match
cnv_file.CnvFile o-- patterns.get_cruise_match_dict
cnv_file.CnvFile o-- xmlcon_parser.get_parser_from_string
cnv_file.CnvFile o-- xmlcon_parser.get_sensor_info

modify_cnv.ModifyCnv o-- modify_cnv.Header
modify_cnv.ModifyCnv o-- modify_cnv.Header
modify_cnv.ModifyCnv o-- modify_cnv.Header
modify_cnv.ModifyCnv o-- modify_cnv.Header
modify_cnv.ModifyCnv o-- modify_cnv.Header
modify_cnv.ModifyCnv o-- modify_cnv.Header
modify_cnv.ModifyCnv o-- modify_cnv.Header
modify_cnv.ModifyCnv o-- modify_cnv.Header
modify_cnv.ModifyCnv o-- cnv_file.Header

patterns.get_cruise_match_dict o-- patterns.get_cruise_match

__init__.get_packages_from_file_list o-- __init__.get_file_object_for_path
__init__.get_packages_from_file_list o-- package.Package

__init__.get_packages_in_directory o-- __init__._get_paths_in_directory_tree
__init__.get_packages_in_directory o-- __init__.get_packages_from_file_list

__init__.get_package_collection_for_directory o-- __init__.get_packages_in_directory

__init__.get_package_for_file o-- __init__._get_paths_in_directory_tree
__init__.get_package_for_file o-- __init__.get_packages_from_file_list

__init__.get_file_names_in_directory o-- __init__.get_packages_in_directory

__init__.update_package_with_files_in_directory o-- __init__._get_paths_in_directory_tree
__init__.update_package_with_files_in_directory o-- __init__.get_file_object_for_path

__init__.rename_package o-- __init__.rename_file_object
__init__.rename_package o-- package.Package

__init__.copy_package o-- __init__.copy_file_object
__init__.copy_package o-- package.Package

file.SeabirdFile o-- mapping.get_year_mapping
file.SeabirdFile o-- mapping.get_ship_mapping
file.SeabirdFile o-- patterns.get_file_stem_match

__init__.modify_cnv_down_file o-- modify_cnv.ModifyCnv

hdr_file.HdrFile o-- patterns.get_cruise_match
hdr_file.HdrFile o-- patterns.get_cruise_match_dict

xmlcon_file.XmlconFile o-- xmlcon_parser.get_parser_from_file
xmlcon_file.XmlconFile o-- xmlcon_parser.get_sensor_info

@enduml